apiVersion: apps/v1
kind: Deployment
metadata:
  name: jp2c
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jp2c
  template:
    metadata:
      labels:
        app: jp2c
    spec:
      containers:
        - name: jp2c
          image: jp2c
          ports:
            - containerPort: 8080   # 기존
            - containerPort: 3000   # 새로 추가
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
---
apiVersion: v1
kind: Service
metadata:
  name: jp2c-service
spec:
  selector:
    app: jp2c
  ports:
    - name: http-8080
      port: 8080
      targetPort: 8080
      nodePort: 30000
    - name: http-3000
      port: 3000
      targetPort: 3000
      nodePort: 30001
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jp2c-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jp2c
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50