apiVersion: apps/v1
kind: Deployment
metadata:
  name: jp2c-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jp2c-redis
  template:
    metadata:
      labels:
        app: jp2c-redis
    spec:
      containers:
        - name: redis
          image: redis:7.4
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: jp2c-redis
spec:
  selector:
    app: jp2c-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP