apiVersion: v1
kind: Secret
metadata:
  name: jp2c-postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: {{ required "Database username required" .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ required "Database password required" .Values.postgres.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jp2c-secret
type: Opaque
stringData:
  JWT_SECRET: {{ required "JWT secret required" .Values.secret.jwtSecret | quote }}