CREATE TABLE verification_codes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expire_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    account_id BIGINT,
    CONSTRAINT pk_verification_codes PRIMARY KEY (id)
);

ALTER TABLE verification_codes
    ADD CONSTRAINT uc_verification_codes_account UNIQUE (account_id);

ALTER TABLE verification_codes
    ADD CONSTRAINT uc_verification_codes_code UNIQUE (code);

ALTER TABLE verification_codes
    ADD CONSTRAINT FK_VERIFICATION_CODES_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES accounts (id);